[project]
name = "ucam-wls-bridge"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = ["authlib", "flask", "requests", "ucam-wls"]
description = "Ucam-WebAuth WLS with an OAuth2 bridge backend."
